global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Reflection;
global using UnityEngine;
global using BepInEx;
global using BepInEx.Configuration;
global using TMPro;
global using Photon.Pun;
global using Photon.Realtime;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using BepInEx.Logging;
global using PlayFab;
global using PlayFab.ClientModels;
global using ExitGames.Client.Photon;
global using UnityEngine.UI;
global using UnityEngine.EventSystems;
global using Hashtable = ExitGames.Client.Photon.Hashtable;
global using GorillaNetworking;
global using FriendInfo = Photon.Realtime.FriendInfo;
global using ButtonType = GorillaPlayerLineButton.ButtonType;
global using Object = UnityEngine.Object;
global using Logger = BepInEx.Logging.Logger;
global using Random = UnityEngine.Random;
global using WeatherType = BetterDayNightManager.WeatherType;
global using UnityEngine.Networking;
global using HarmonyLib;
global using System.IO.Pipes;

