<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>ScryptoUtilsPad</RootNamespace>
    <AssemblyName>ScryptoUtilsPad</AssemblyName>
    <Version>1.0.0</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
    <DefaultItemExcludes>$(DefaultItemExcludes);Libs\**;Libs_pub\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\JetBrainsMono-Bold.ttf"><LogicalName>ScryptoUtilsPad.Resources.JetBrainsMono-Bold.ttf</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\pixel.ttf"><LogicalName>ScryptoUtilsPad.Resources.pixel.ttf</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\MetaLogo.png"><LogicalName>ScryptoUtilsPad.Resources.MetaLogo.png</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\OculusLogo.png"><LogicalName>ScryptoUtilsPad.Resources.OculusLogo.png</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\SteamLogo.png"><LogicalName>ScryptoUtilsPad.Resources.SteamLogo.png</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\QuickSong.exe"><LogicalName>ScryptoUtilsPad.Resources.QuickSong.exe</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\cychecker"><LogicalName>ScryptoUtilsPad.Resources.cychecker</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Clicky.wav"><LogicalName>ScryptoUtilsPad.Resources.Clicky.wav</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Woody Click.wav"><LogicalName>ScryptoUtilsPad.Resources.Woody Click.wav</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Border.wav"><LogicalName>ScryptoUtilsPad.Resources.Border.wav</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Creamy.wav"><LogicalName>ScryptoUtilsPad.Resources.Creamy.wav</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Splash.wav"><LogicalName>ScryptoUtilsPad.Resources.Splash.wav</LogicalName></EmbeddedResource>
    <EmbeddedResource Include="Resources\Half-Life.wav"><LogicalName>ScryptoUtilsPad.Resources.Half-Life.wav</LogicalName></EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Libs\*.dll" Exclude="Libs\System.*;Libs\netstandard.dll;Libs\mscorlib.dll;Libs\Microsoft.*.dll">
      <HintPath>%(Identity)</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" />
    <Publicize Include="Assembly-CSharp" />
  </ItemGroup>

</Project>
