[assembly: System.Reflection.AssemblyCompany("ScryptoUtilsPad")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.3")]
[assembly: System.Reflection.AssemblyProduct("SUPC")]
[assembly: System.Reflection.AssemblyTitle("SUPC - Scrypto Utils Pad Continued")]
[assembly: System.Reflection.AssemblyVersion("2.0.3.0")]
